###GIT Details ###
GIT_CRED_ID=ashkuma
GIT_URL=https://git.dhl.com/ESB/ESB-wM-OpenShift.git

###Openshift Details###
OC_URL=https://api.czchooct005.dhl.com:6443

### EMail Details ###
USER_EMAIL=ashok.kumar1@dhl.com
USER_NAME=ashkuma

###Backup Image Details###
BACKUP_STRING=-backup

####Artifactory Details####
